
services:
  # NEXTJS FRONTEND
  frontend:
    container_name: frontend-container
    image: ghcr.io/edoandcode/devblog-app-frontend-image:latest
    build:
      context: ../../frontend
      dockerfile: Dockerfile.production
      args:
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        NEXT_PUBLIC_BASE_PATH: ${NEXT_PUBLIC_BASE_PATH}
        NEXT_PUBLIC_API_ENDPOINT: ${NEXT_PUBLIC_API_ENDPOINT}
        NEXT_PUBLIC_API_TOKEN: ${NEXT_PUBLIC_API_TOKEN}

    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    name: frontend
    driver: bridge