name: Build, Push and Deploy Frontend to Production

on:
  push:
    branches:
      - frontend

jobs:     

  build_and_push_frontend:
   ## needs: deploy_backend
    runs-on: ubuntu-latest
    environment: production 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Inject token in .npmrc
        run: |
          mkdir -p ./frontend
          echo "registry=https://registry.npmjs.org/" > frontend/.npmrc
          echo "@edoandcode:registry=https://npm.pkg.github.com/" >> frontend/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PAT }}" >> frontend/.npmrc
          cat frontend/.npmrc

      - name: Build and Push Frontend Image
        working-directory: ./_deployment/docker
        env:
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          NEXT_PUBLIC_BASE_PATH: ${{ secrets.NEXT_PUBLIC_BASE_PATH }}
          NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.NEXT_PUBLIC_API_ENDPOINT }}
        run: |
          docker compose -f docker-compose.frontend-build.yaml build frontend
          docker compose -f docker-compose.frontend-build.yaml push frontend

  deploy_all:
    needs: build_and_push_frontend
    runs-on: ubuntu-latest
    environment: production

    steps: 
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_IP_ADDRESS }} >> ~/.ssh/known_hosts

      - name: Deploy All
        run: | 
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VPS_IP_ADDRESS }} "
            echo '${{ secrets.GH_PAT }}' | docker login ghcr.io -u '${{ secrets.GH_USERNAME }}' --password-stdin &&
            cd ${{ secrets.REMOTE_APP_DIRECTORY }}/_deployment/docker &&
            docker compose --file docker-compose.deploy-all.yaml down --remove-orphans &&
            docker compose --file docker-compose.deploy-all.yaml pull backend frontend &&
            docker compose --file docker-compose.deploy-all.yaml up -d
          "
      
      - name: cleanup
        run: rm -rf ~/.ssh